image: tiangolo/docker-with-compose

stages:
  - build_image
  - push
  - push_version
  - update_k8s

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build_image:
  tags:
    - docker
    - linux
  stage: build_image
  script:
    - docker build . -t docker.idiap.ch/wenet/activities_prodictor:latest
    - docker build -f Dockerfile_slim . -t docker.idiap.ch/wenet/activities_prodictor:latest-slim

push:
  tags:
    - docker
    - linux
  stage: push
  only:
    - master
  script:
    - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
    - docker push docker.idiap.ch/wenet/activities_prodictor:latest
    - docker push docker.idiap.ch/wenet/activities_prodictor:latest-slim
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
    - docker tag docker.idiap.ch/wenet/activities_prodictor:latest internetofus/activities_prodictor:latest
    - docker push internetofus/activities_prodictor:latest
push_version:
  tags:
    - docker
    - linux
  stage: push_version
  only:
    - tags
  script:
    - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
    - docker tag  docker.idiap.ch/wenet/activities_prodictor:latest docker.idiap.ch/wenet/activities_prodictor:$CI_COMMIT_TAG
    - docker push docker.idiap.ch/wenet/activities_prodictor:$CI_COMMIT_TAG
    - docker tag  docker.idiap.ch/wenet/activities_prodictor:latest-slim docker.idiap.ch/wenet/activities_prodictor:$CI_COMMIT_TAG-slim
    - docker push docker.idiap.ch/wenet/activities_prodictor:$CI_COMMIT_TAG-slim
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
    - docker tag docker.idiap.ch/wenet/activities_prodictor:$CI_COMMIT_TAG internetofus/activities_prodictor:$CI_COMMIT_TAG
    - docker push internetofus/activities_prodictor:$CI_COMMIT_TAG
update_k8s:
  tags:
    - docker
    - linux
  stage: update_k8s
  image: google/cloud-sdk
  retry: 2
  script:
    - mkdir -p $HOME/.kube
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - kubectl rollout restart deployment.apps/wenet-activities-predictor-deployment
