# SPDX-FileCopyrightText: Copyright © 2022 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    - id: isort # sort imports
      args: [--sl, --profile=black]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black # code formatter
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args:
            - "--autofix"
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.254'
    hooks:
      - id: ruff

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 7e1ceac2d5967f5428f0b1900cb7fe26da724bb1
    hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [feat, fix, docs, chore, ci, build] # optional: list of Conventional Commits types to allow
